// Auto-generated script template
// Generated by EDIT2

Goto EndOfTemplate
:LoadTemplate

LoadTileSet "data/tileset/tileset.bmp"
LoadTileMap "data/map/map.dat"

Player Position 42 1

Object Clear

Trigger 38 14 Map_Sign
Trigger 39 14 Map_Sign
Trigger 38 15 Map_Sign
Trigger 39 15 Map_Sign
Goto Main

// Trigger code segments
:Map_Sign
// Action button flag
// Auto-generated trigger segment
Dialouge "It's a sign"
Goto Main

// End of Auto-generated template
:EndOfTemplate

