// Auto-generated script template
// Generated by EDIT2

Goto EndOfTemplate
:LoadTemplate

LoadTileSet "data/tileset/tileset.bmp"
LoadTileMap "data/map/testmap.dat"

Player Position 14 4

Object Clear

Goto Main

// Trigger code segments
// End of Auto-generated template
:EndOfTemplate
